#===============================================================================
# Autonomous Vehicle Library
#
# Description: Gyrocompass message containing attitude and its standard
#              deviations. If a value is not known, use NaN.
#===============================================================================

float64 roll      # Roll in radians
float64 pitch     # Pitch in radians
float64 yaw       # Yaw in radians
float64 roll_std  # Roll standard deviation in radians
float64 pitch_std # Pitch standard deviation in radians
float64 yaw_std   # Yaw standard deviation in radians
