#===============================================================================
# Autonomous Vehicle Library
#
# PURPOSE: Describes a Springnav INS lnavutc message containing information about
#          vehicle navigation information.
#
# AUTHOR:  cong
#===============================================================================

float64 lat       # Latitude in decimal deg
float64 lon       # Longitude in decimal deg
float32 dep       # Depth in meters
float32 alt       # Altitude in meters
float32 roll      # Roll in deg
float32 pitch     # Pitch in deg
float32 heading   # Heading in deg
