#===============================================================================
# Autonomous Vehicle Library
#
# PURPOSE: Describes a Springnav INS obstsvs message containing information about
#          vehicle status information.
#
# AUTHOR:  cong
#===============================================================================

uint8 obmsgtype         # Observation type:
                        # 0 – VALEPORT
                        # 1 – $PSONSS
                        # 2 – Manual
                        # 3 – Auto
