#===============================================================================
# Autonomous Vehicle Library
#
# PURPOSE: Describes a Springnav INS obstgpspos message containing information about
#          vehicle status information.
#
# AUTHOR:  cong
#===============================================================================

float32 reslat        # Residual latitude in rad
float32 reslon        # Residual longitude, in rad
float32 resdepth      # Residual, depth zero if 2d, in m
