#===============================================================================
# Autonomous Vehicle Library
#
# Description: Describes a DVL message.
#===============================================================================

float64 vx   # x-axis velocity in m/s
float64 vy   # y-axis velocity in m/s
float64 vz   # z-axis velocity in m/s
float64 ve   # velocity error in m/s
bool valid   # Data is valid
