#===============================================================================
# Autonomous Vehicle Library
#
# Description: Describes a message used to relay the status of the safety node.
#===============================================================================

# Safety mode that the safety node is currently in
uint8 status

# String description of the current safety status
string message
