#===============================================================================
# Autonomous Vehicle Library
#
# PURPOSE: For 2g actuator. Describes a Fins message containing fin angles in
#          degrees relative to the fin's local axis. Follows the right hand rule
#          by pointing the thumb along the fin axis away from the vehicle, and
#          the fingers curl along the positive angle direction.
#
# AUTHOR: Cong
#===============================================================================


int32 position_setpoint1   #The absolute position shaft rotate millidegrees.
int32 position_setpoint2   #The absolute position shaft rotate millidegrees.
int32 position_setpoint3   #The absolute position shaft rotate millidegrees.
int32 position_setpoint4   #The absolute position shaft rotate millidegrees.
