#===============================================================================
# Autonomous Vehicle Library
#
# Description: An action definition containing information about a mission
#              action.
#===============================================================================

#===============================================================================
#                              GOAL DEFINITION
#===============================================================================

# Packet containing the action parameters
uint8[] packet

---
#===============================================================================
#                              RESULT DEFINITION
#===============================================================================

# Indicates whether the action was completed successfully
bool success

---
#===============================================================================
#                              FEEDBACK DEFINITION
#===============================================================================

# Indicates the percentage of action completion
float64 percent
